// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findByEmail = `-- name: FindByEmail :one
SELECT id, email, password, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByID = `-- name: FindByID :one
SELECT id, email, password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) FindByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const save = `-- name: Save :one
INSERT INTO users (id, email, password) VALUES ($1, $2, $3)
RETURNING id, email, created_at, updated_at
`

type SaveParams struct {
	ID       uuid.UUID
	Email    string
	Password string
}

type SaveRow struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) (SaveRow, error) {
	row := q.db.QueryRow(ctx, save, arg.ID, arg.Email, arg.Password)
	var i SaveRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
